function options = configure(varargin)
  options = Configure.systemSimulation(varargin{:});
  options = Configure.processVariation(options);
  options = Configure.polynomialChaos(options);

  options.steadyStateOptions = Options( ...
    'algorithm', 'condensedEquation', ...
    'version', 1, ...
    'iterationLimit', 20, ...
    'temperatureLimit', Utils.toKelvin(1e3), ...
    'tolerance', 0.5);
end
