function speedWithSteps
  speed( ...
    'range', [ 1e1 1e2 1e3 1e4 1e5 ], ...
    'repeat', [ 10 10 10 10 10 ], ...
    'configure', @(stepCount) Configure.problem( ...
      'processorCount', 4, 'stepCount', stepCount));
end
